### ISSUE TITLE
数据库中表创建失败

### ISSUE THREAD

**Issue by Libestor** [bot-ssttkkl/nonebot-plugin-access-control#2]
![image](https://user-images.githubusercontent.com/87460425/229975520-aef4dd40-6888-4b18-b0cb-5c380d304a6a.png)
错误描述：
安装后有生成db文件，但是没有写入表，之后不论是写入还是错误都会触发
内部错误：<class 'sqlalchemy.exc.OperationalError'>(sqlite3.OperationalError) no such table: nonebot_plugin_access_control_permission
错误报告

**Comment by ssttkkl** [comment]
可以尝试参考 https://github.com/he0119/nonebot-plugin-datastore#%E6%95%B0%E6%8D%AE%E5%BA%93%E8%BF%81%E7%A7%BB 执行数据库迁移
