### ISSUE TITLE
有没有办法兼容pydanticV1

### ISSUE THREAD

**Issue by MoonofBridge24** [bot-ssttkkl/nonebot-plugin-access-control#31]
有一部分插件年久失修(确信)，无法使用pydanticV2加载，但是大部分都能用V1加载，有没有办法让ac也能在V1加载

**Comment by leafliber** [comment]
遇到了同样的问题
现在回退到了版本1.1.4，目前可用
值得注意的是，可能会遇到nonebot_plugin_session 0.2.3版本冲突问题，需要cd到环境目录升级插件
`pip install nonebot_plugin_session==0.3.1`
仍然会显示nonebot-plugin-access-control 1.1.5 requires nonebot-plugin-session<0.3.0,>=0.2.0, but you have nonebot-plugin-session 0.3.1 which is incompatible.
但是可以使用
